/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * OAuth settings for the connection provider
 *
 */
class ApiOAuthSettings {
  /**
   * Create a ApiOAuthSettings.
   * @property {string} [identityProvider] Identity provider
   * @property {string} [clientId] Resource provider client id
   * @property {string} [clientSecret] Client Secret needed for OAuth
   * @property {array} [scopes] OAuth scopes
   * @property {string} [redirectUrl] Url
   * @property {object} [properties] Read only properties for this oauth
   * setting.
   * @property {object} [customParameters] OAuth parameters key is the name of
   * parameter
   */
  constructor() {
  }

  /**
   * Defines the metadata of ApiOAuthSettings
   *
   * @returns {object} metadata of ApiOAuthSettings
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ApiOAuthSettings',
      type: {
        name: 'Composite',
        className: 'ApiOAuthSettings',
        modelProperties: {
          identityProvider: {
            required: false,
            serializedName: 'identityProvider',
            type: {
              name: 'String'
            }
          },
          clientId: {
            required: false,
            serializedName: 'clientId',
            type: {
              name: 'String'
            }
          },
          clientSecret: {
            required: false,
            serializedName: 'clientSecret',
            type: {
              name: 'String'
            }
          },
          scopes: {
            required: false,
            serializedName: 'scopes',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          redirectUrl: {
            required: false,
            serializedName: 'redirectUrl',
            type: {
              name: 'String'
            }
          },
          properties: {
            required: false,
            serializedName: 'properties',
            type: {
              name: 'Object'
            }
          },
          customParameters: {
            required: false,
            serializedName: 'customParameters',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'ApiOAuthSettingsParameterElementType',
                  type: {
                    name: 'Composite',
                    className: 'ApiOAuthSettingsParameter'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = ApiOAuthSettings;
