/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * OAuth Settings Parameter
 *
 */
class ApiOAuthSettingsParameter {
  /**
   * Create a ApiOAuthSettingsParameter.
   * @property {string} [value] Value
   * @property {object} [options] Read only: Options available to this
   * parameter
   * @property {object} [uiDefinition] UI definitions per culture as caller can
   * specify the culture
   */
  constructor() {
  }

  /**
   * Defines the metadata of ApiOAuthSettingsParameter
   *
   * @returns {object} metadata of ApiOAuthSettingsParameter
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ApiOAuthSettingsParameter',
      type: {
        name: 'Composite',
        className: 'ApiOAuthSettingsParameter',
        modelProperties: {
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'String'
            }
          },
          options: {
            required: false,
            serializedName: 'options',
            type: {
              name: 'Object'
            }
          },
          uiDefinition: {
            required: false,
            serializedName: 'uiDefinition',
            type: {
              name: 'Object'
            }
          }
        }
      }
    };
  }
}

module.exports = ApiOAuthSettingsParameter;
