/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Collection of Apis
 */
class ApisCollection extends Array {
  /**
   * Create a ApisCollection.
   * @property {string} [nextLink] Link to next page of resources
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ApisCollection
   *
   * @returns {object} metadata of ApisCollection
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ApisCollection',
      type: {
        name: 'Composite',
        className: 'ApisCollection',
        modelProperties: {
          value: {
            required: false,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ApiEntityElementType',
                  type: {
                    name: 'Composite',
                    className: 'ApiEntity'
                  }
              }
            }
          },
          nextLink: {
            required: false,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ApisCollection;
