/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The plan object in an ARM, represents a marketplace plan
 *
 */
class ArmPlan {
  /**
   * Create a ArmPlan.
   * @property {string} [name] The name
   * @property {string} [publisher] The publisher
   * @property {string} [product] The product
   * @property {string} [promotionCode] The promotion code
   * @property {string} [version] Version of product
   */
  constructor() {
  }

  /**
   * Defines the metadata of ArmPlan
   *
   * @returns {object} metadata of ArmPlan
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ArmPlan',
      type: {
        name: 'Composite',
        className: 'ArmPlan',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          publisher: {
            required: false,
            serializedName: 'publisher',
            type: {
              name: 'String'
            }
          },
          product: {
            required: false,
            serializedName: 'product',
            type: {
              name: 'String'
            }
          },
          promotionCode: {
            required: false,
            serializedName: 'promotionCode',
            type: {
              name: 'String'
            }
          },
          version: {
            required: false,
            serializedName: 'version',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ArmPlan;
