/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * API definitions with backend urls
 *
 * @extends models['Resource']
 */
class BackendServiceDefinition extends models['Resource'] {
  /**
   * Create a BackendServiceDefinition.
   * @property {string} [serviceUrl] Url from which the swagger payload will be
   * fetched
   * @property {array} [hostingEnvironmentServiceUrls] Service Urls per Hosting
   * environment
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of BackendServiceDefinition
   *
   * @returns {object} metadata of BackendServiceDefinition
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'BackendServiceDefinition',
      type: {
        name: 'Composite',
        className: 'BackendServiceDefinition',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          kind: {
            required: false,
            serializedName: 'kind',
            type: {
              name: 'String'
            }
          },
          location: {
            required: true,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          serviceUrl: {
            required: false,
            serializedName: 'properties.serviceUrl',
            type: {
              name: 'String'
            }
          },
          hostingEnvironmentServiceUrls: {
            required: false,
            serializedName: 'properties.hostingEnvironmentServiceUrls',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'HostingEnvironmentServiceDescriptionsElementType',
                  type: {
                    name: 'Composite',
                    className: 'HostingEnvironmentServiceDescriptions'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = BackendServiceDefinition;
