/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Confirm Consent Code Input payload
 *
 * @extends models['Resource']
 */
class ConfirmConsentCodeInput extends models['Resource'] {
  /**
   * Create a ConfirmConsentCodeInput.
   * @property {string} [principalType] Principal type. Possible values
   * include: 'ActiveDirectory', 'Connection', 'MicrosoftAccount'
   * @property {string} [tenantId] Tenant Id
   * @property {string} [objectId] AAD object ID. This is userId
   * @property {string} [code] Code that was returned during consent flow
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ConfirmConsentCodeInput
   *
   * @returns {object} metadata of ConfirmConsentCodeInput
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ConfirmConsentCodeInput',
      type: {
        name: 'Composite',
        className: 'ConfirmConsentCodeInput',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          kind: {
            required: false,
            serializedName: 'kind',
            type: {
              name: 'String'
            }
          },
          location: {
            required: true,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          principalType: {
            required: false,
            serializedName: 'properties.principalType',
            type: {
              name: 'Enum',
              allowedValues: [ 'ActiveDirectory', 'Connection', 'MicrosoftAccount' ]
            }
          },
          tenantId: {
            required: false,
            serializedName: 'properties.tenantId',
            type: {
              name: 'String'
            }
          },
          objectId: {
            required: false,
            serializedName: 'properties.objectId',
            type: {
              name: 'String'
            }
          },
          code: {
            required: false,
            serializedName: 'properties.code',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ConfirmConsentCodeInput;
