/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a ConnectionSecrets.
 */
class ConnectionSecrets {
  /**
   * Create a ConnectionSecrets.
   * @property {object} [parameterValues] Tokens/Claim
   * @property {string} [connectionKey] Connection Key
   */
  constructor() {
  }

  /**
   * Defines the metadata of ConnectionSecrets
   *
   * @returns {object} metadata of ConnectionSecrets
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ConnectionSecrets',
      type: {
        name: 'Composite',
        className: 'ConnectionSecrets',
        modelProperties: {
          parameterValues: {
            required: false,
            serializedName: 'parameterValues',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'ObjectElementType',
                  type: {
                    name: 'Object'
                  }
              }
            }
          },
          connectionKey: {
            required: false,
            serializedName: 'connectionKey',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ConnectionSecrets;
