/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Connection status
 *
 * @extends models['Resource']
 */
class ConnectionStatus extends models['Resource'] {
  /**
   * Create a ConnectionStatus.
   * @property {string} [status] Status
   * @property {string} [target] Target of the error
   * @property {object} [error] Error details
   * @property {string} [error.code] code of the status
   * @property {string} [error.message] Description of the status
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ConnectionStatus
   *
   * @returns {object} metadata of ConnectionStatus
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ConnectionStatus',
      type: {
        name: 'Composite',
        className: 'ConnectionStatus',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          kind: {
            required: false,
            serializedName: 'kind',
            type: {
              name: 'String'
            }
          },
          location: {
            required: true,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          status: {
            required: false,
            serializedName: 'properties.status',
            type: {
              name: 'String'
            }
          },
          target: {
            required: false,
            serializedName: 'properties.target',
            type: {
              name: 'String'
            }
          },
          error: {
            required: false,
            serializedName: 'properties.error',
            type: {
              name: 'Composite',
              className: 'ConnectionError'
            }
          }
        }
      }
    };
  }
}

module.exports = ConnectionStatus;
