/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a ConsentLink.
 */
class ConsentLink {
  /**
   * Create a ConsentLink.
   * @property {string} [link] Uri for the consent link
   * @property {string} [firstPartyLoginUri] Uri for first party login
   * @property {string} [displayName] Display Name of the parameter in the
   * connection provider's oauthSettings
   * @property {string} [status] Status of the link. Possible values include:
   * 'Unauthenticated', 'Authenticated', 'Error'
   */
  constructor() {
  }

  /**
   * Defines the metadata of ConsentLink
   *
   * @returns {object} metadata of ConsentLink
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ConsentLink',
      type: {
        name: 'Composite',
        className: 'ConsentLink',
        modelProperties: {
          link: {
            required: false,
            serializedName: 'link',
            type: {
              name: 'String'
            }
          },
          firstPartyLoginUri: {
            required: false,
            serializedName: 'firstPartyLoginUri',
            type: {
              name: 'String'
            }
          },
          displayName: {
            required: false,
            serializedName: 'displayName',
            type: {
              name: 'String'
            }
          },
          status: {
            required: false,
            serializedName: 'status',
            type: {
              name: 'Enum',
              allowedValues: [ 'Unauthenticated', 'Authenticated', 'Error' ]
            }
          }
        }
      }
    };
  }
}

module.exports = ConsentLink;
