/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a ConsentLinkInputParameter.
 */
class ConsentLinkInputParameter {
  /**
   * Create a ConsentLinkInputParameter.
   * @property {string} [principalType] Principal type. Possible values
   * include: 'ActiveDirectory', 'Connection', 'MicrosoftAccount'
   * @property {string} [tenantId] Tenant Id
   * @property {string} [objectId] AAD OID (user or group) if the principal
   * type is ActiveDirectory.
   * MSA PUID if the principal type is MicrosoftAccount.
   * @property {string} [parameterName] Name of the parameter in the connection
   * provider's oauthSettings
   * @property {string} [redirectUrl] Name of the parameter in the connection
   * provider's oauthSettings
   */
  constructor() {
  }

  /**
   * Defines the metadata of ConsentLinkInputParameter
   *
   * @returns {object} metadata of ConsentLinkInputParameter
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ConsentLinkInputParameter',
      type: {
        name: 'Composite',
        className: 'ConsentLinkInputParameter',
        modelProperties: {
          principalType: {
            required: false,
            serializedName: 'principalType',
            type: {
              name: 'Enum',
              allowedValues: [ 'ActiveDirectory', 'Connection', 'MicrosoftAccount' ]
            }
          },
          tenantId: {
            required: false,
            serializedName: 'tenantId',
            type: {
              name: 'String'
            }
          },
          objectId: {
            required: false,
            serializedName: 'objectId',
            type: {
              name: 'String'
            }
          },
          parameterName: {
            required: false,
            serializedName: 'parameterName',
            type: {
              name: 'String'
            }
          },
          redirectUrl: {
            required: false,
            serializedName: 'redirectUrl',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ConsentLinkInputParameter;
