/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Custom logging setting value
 *
 * @extends models['Resource']
 */
class CustomLoginSettingValue extends models['Resource'] {
  /**
   * Create a CustomLoginSettingValue.
   * @property {string} [option] Option selected for this custom login setting
   * value
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of CustomLoginSettingValue
   *
   * @returns {object} metadata of CustomLoginSettingValue
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CustomLoginSettingValue',
      type: {
        name: 'Composite',
        className: 'CustomLoginSettingValue',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          kind: {
            required: false,
            serializedName: 'kind',
            type: {
              name: 'String'
            }
          },
          location: {
            required: true,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          option: {
            required: false,
            serializedName: 'properties.option',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = CustomLoginSettingValue;
