/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * expanded parent object for expansion
 *
 * @extends models['Resource']
 */
class ExpandedParentApiEntity extends models['Resource'] {
  /**
   * Create a ExpandedParentApiEntity.
   * @property {string} [expandedParentApiEntityId] Id of connection provider
   * @property {object} [entity] Id of connection provider
   * @property {string} [entity.id] Resource Id. Typically id is populated only
   * for responses to GET requests. Caller is responsible for passing in this
   * value for GET requests only.
   * For example:
   * /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupId}/providers/Microsoft.Web/sites/{sitename}
   * @property {string} [entity.name] Name of resource
   * @property {string} [entity.type] Type of resource e.g Microsoft.Web/sites
   * @property {string} [entity.location] Geo region resource belongs to e.g.
   * SouthCentralUS, SouthEastAsia
   * @property {object} [entity.tags] Tags associated with resource
   * @property {object} [entity.plan] Azure resource manager plan
   * @property {string} [entity.plan.name] The name
   * @property {string} [entity.plan.publisher] The publisher
   * @property {string} [entity.plan.product] The product
   * @property {string} [entity.plan.promotionCode] The promotion code
   * @property {string} [entity.plan.version] Version of product
   * @property {object} [entity.properties] Resource specific properties
   * @property {string} [entity.properties.apiEntityName] Name of the API
   * the URL path of this API when exposed via APIM
   * @property {object} [entity.properties.generalInformation] the URL path of
   * this API when exposed via APIM
   * @property {string} [entity.properties.generalInformation.iconUrl] Icon Url
   * @property {string} [entity.properties.generalInformation.displayName]
   * Display Name
   * @property {string} [entity.properties.generalInformation.description]
   * Description
   * @property {string} [entity.properties.generalInformation.termsOfUseUrl] a
   * public accessible url of the Terms Of Use Url of this API
   * @property {string}
   * [entity.properties.generalInformation.connectionDisplayName]
   * DefaultConnectionNameTemplate
   * @property {object}
   * [entity.properties.generalInformation.connectionPortalUrl]
   * ConnectionPortalUrl
   * @property {string} [entity.properties.path] the URL path of this API when
   * exposed via APIM
   * @property {array} [entity.properties.runtimeUrls] Read only property
   * returning the runtime endpoints where the API can be called
   * @property {array} [entity.properties.protocols] Protocols supported by the
   * front end - http/https
   * @property {object} [entity.properties.policies] API policies
   * @property {string} [entity.properties.policies.content] Content of xml
   * policy
   * @property {object} [entity.properties.backendService] Backend service
   * definition
   * @property {string} [entity.properties.backendService.serviceUrl] Url from
   * which the swagger payload will be fetched
   * @property {array}
   * [entity.properties.backendService.hostingEnvironmentServiceUrls] Service
   * Urls per Hosting environment
   * @property {string} [entity.properties.apiDefinitionUrl] API definition Url
   * - url where the swagger can be downloaded from
   * @property {object} [entity.properties.metadata] Free form object for the
   * data caller wants to store
   * @property {array} [entity.properties.capabilities] Capabilities
   * @property {object} [entity.properties.connectionParameters] Connection
   * parameters
   * @property {date} [entity.properties.createdTime] Timestamp of the
   * connection creation
   * @property {date} [entity.properties.changedTime] Timestamp of last
   * connection change.
   * @property {object} [entity.sku] Sku description of the resource
   * @property {string} [entity.sku.name] Name of the resource sku
   * @property {string} [entity.sku.tier] Service Tier of the resource sku
   * @property {string} [entity.sku.size] Size specifier of the resource sku
   * @property {string} [entity.sku.family] Family code of the resource sku
   * @property {number} [entity.sku.capacity] Current number of instances
   * assigned to the resource
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ExpandedParentApiEntity
   *
   * @returns {object} metadata of ExpandedParentApiEntity
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ExpandedParent_ApiEntity_',
      type: {
        name: 'Composite',
        className: 'ExpandedParentApiEntity',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          kind: {
            required: false,
            serializedName: 'kind',
            type: {
              name: 'String'
            }
          },
          location: {
            required: true,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          expandedParentApiEntityId: {
            required: false,
            serializedName: 'properties.id',
            type: {
              name: 'String'
            }
          },
          entity: {
            required: false,
            serializedName: 'properties.entity',
            type: {
              name: 'Composite',
              className: 'ResponseMessageEnvelopeApiEntity'
            }
          }
        }
      }
    };
  }
}

module.exports = ExpandedParentApiEntity;
