/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * General API information
 *
 * @extends models['Resource']
 */
class GeneralApiInformation extends models['Resource'] {
  /**
   * Create a GeneralApiInformation.
   * @property {string} [iconUrl] Icon Url
   * @property {string} [displayName] Display Name
   * @property {string} [description] Description
   * @property {string} [termsOfUseUrl] a public accessible url of the Terms Of
   * Use Url of this API
   * @property {string} [connectionDisplayName] DefaultConnectionNameTemplate
   * @property {object} [connectionPortalUrl] ConnectionPortalUrl
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of GeneralApiInformation
   *
   * @returns {object} metadata of GeneralApiInformation
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'GeneralApiInformation',
      type: {
        name: 'Composite',
        className: 'GeneralApiInformation',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          kind: {
            required: false,
            serializedName: 'kind',
            type: {
              name: 'String'
            }
          },
          location: {
            required: true,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          iconUrl: {
            required: false,
            serializedName: 'properties.iconUrl',
            type: {
              name: 'String'
            }
          },
          displayName: {
            required: false,
            serializedName: 'properties.displayName',
            type: {
              name: 'String'
            }
          },
          description: {
            required: false,
            serializedName: 'properties.description',
            type: {
              name: 'String'
            }
          },
          termsOfUseUrl: {
            required: false,
            serializedName: 'properties.termsOfUseUrl',
            type: {
              name: 'String'
            }
          },
          connectionDisplayName: {
            required: false,
            serializedName: 'properties.connectionDisplayName',
            type: {
              name: 'String'
            }
          },
          connectionPortalUrl: {
            required: false,
            serializedName: 'properties.connectionPortalUrl',
            type: {
              name: 'Object'
            }
          }
        }
      }
    };
  }
}

module.exports = GeneralApiInformation;
