/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

var msRestAzure = require('ms-rest-azure');

exports.BaseResource = msRestAzure.BaseResource;
exports.CloudError = msRestAzure.CloudError;
exports.Resource = require('./resource');
exports.GeneralApiInformation = require('./generalApiInformation');
exports.ApiPolicies = require('./apiPolicies');
exports.HostingEnvironmentServiceDescriptions = require('./hostingEnvironmentServiceDescriptions');
exports.BackendServiceDefinition = require('./backendServiceDefinition');
exports.ApiOAuthSettingsParameter = require('./apiOAuthSettingsParameter');
exports.ApiOAuthSettings = require('./apiOAuthSettings');
exports.ConnectionParameter = require('./connectionParameter');
exports.ApiEntity = require('./apiEntity');
exports.ConnectionError = require('./connectionError');
exports.ConnectionStatus = require('./connectionStatus');
exports.CustomLoginSettingValue = require('./customLoginSettingValue');
exports.ParameterCustomLoginSettingValues = require('./parameterCustomLoginSettingValues');
exports.ArmPlan = require('./armPlan');
exports.SkuDescription = require('./skuDescription');
exports.ResponseMessageEnvelopeApiEntity = require('./responseMessageEnvelopeApiEntity');
exports.ExpandedParentApiEntity = require('./expandedParentApiEntity');
exports.Connection = require('./connection');
exports.ConsentLinkInputParameter = require('./consentLinkInputParameter');
exports.ConsentLinkInput = require('./consentLinkInput');
exports.ConsentLink = require('./consentLink');
exports.ConsentLinkPayload = require('./consentLinkPayload');
exports.ListConnectionKeysInput = require('./listConnectionKeysInput');
exports.ConnectionSecrets = require('./connectionSecrets');
exports.ConfirmConsentCodeInput = require('./confirmConsentCodeInput');
exports.ApisCollection = require('./apisCollection');
exports.ConnectionCollection = require('./connectionCollection');
