/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Message envelope that contains the common Azure resource manager properties
 * and the resource provider specific content
 *
 */
class ResponseMessageEnvelopeApiEntity {
  /**
   * Create a ResponseMessageEnvelopeApiEntity.
   * @property {string} [id] Resource Id. Typically id is populated only for
   * responses to GET requests. Caller is responsible for passing in this
   * value for GET requests only.
   * For example:
   * /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupId}/providers/Microsoft.Web/sites/{sitename}
   * @property {string} [name] Name of resource
   * @property {string} [type] Type of resource e.g Microsoft.Web/sites
   * @property {string} [location] Geo region resource belongs to e.g.
   * SouthCentralUS, SouthEastAsia
   * @property {object} [tags] Tags associated with resource
   * @property {object} [plan] Azure resource manager plan
   * @property {string} [plan.name] The name
   * @property {string} [plan.publisher] The publisher
   * @property {string} [plan.product] The product
   * @property {string} [plan.promotionCode] The promotion code
   * @property {string} [plan.version] Version of product
   * @property {object} [properties] Resource specific properties
   * @property {string} [properties.apiEntityName] Name of the API
   * the URL path of this API when exposed via APIM
   * @property {object} [properties.generalInformation] the URL path of this
   * API when exposed via APIM
   * @property {string} [properties.generalInformation.iconUrl] Icon Url
   * @property {string} [properties.generalInformation.displayName] Display
   * Name
   * @property {string} [properties.generalInformation.description] Description
   * @property {string} [properties.generalInformation.termsOfUseUrl] a public
   * accessible url of the Terms Of Use Url of this API
   * @property {string} [properties.generalInformation.connectionDisplayName]
   * DefaultConnectionNameTemplate
   * @property {object} [properties.generalInformation.connectionPortalUrl]
   * ConnectionPortalUrl
   * @property {string} [properties.path] the URL path of this API when exposed
   * via APIM
   * @property {array} [properties.runtimeUrls] Read only property returning
   * the runtime endpoints where the API can be called
   * @property {array} [properties.protocols] Protocols supported by the front
   * end - http/https
   * @property {object} [properties.policies] API policies
   * @property {string} [properties.policies.content] Content of xml policy
   * @property {object} [properties.backendService] Backend service definition
   * @property {string} [properties.backendService.serviceUrl] Url from which
   * the swagger payload will be fetched
   * @property {array}
   * [properties.backendService.hostingEnvironmentServiceUrls] Service Urls per
   * Hosting environment
   * @property {string} [properties.apiDefinitionUrl] API definition Url - url
   * where the swagger can be downloaded from
   * @property {object} [properties.metadata] Free form object for the data
   * caller wants to store
   * @property {array} [properties.capabilities] Capabilities
   * @property {object} [properties.connectionParameters] Connection parameters
   * @property {date} [properties.createdTime] Timestamp of the connection
   * creation
   * @property {date} [properties.changedTime] Timestamp of last connection
   * change.
   * @property {object} [sku] Sku description of the resource
   * @property {string} [sku.name] Name of the resource sku
   * @property {string} [sku.tier] Service Tier of the resource sku
   * @property {string} [sku.size] Size specifier of the resource sku
   * @property {string} [sku.family] Family code of the resource sku
   * @property {number} [sku.capacity] Current number of instances assigned to
   * the resource
   */
  constructor() {
  }

  /**
   * Defines the metadata of ResponseMessageEnvelopeApiEntity
   *
   * @returns {object} metadata of ResponseMessageEnvelopeApiEntity
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ResponseMessageEnvelope_ApiEntity_',
      type: {
        name: 'Composite',
        className: 'ResponseMessageEnvelopeApiEntity',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          location: {
            required: false,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          plan: {
            required: false,
            serializedName: 'plan',
            type: {
              name: 'Composite',
              className: 'ArmPlan'
            }
          },
          properties: {
            required: false,
            serializedName: 'properties',
            type: {
              name: 'Composite',
              className: 'ApiEntity'
            }
          },
          sku: {
            required: false,
            serializedName: 'sku',
            type: {
              name: 'Composite',
              className: 'SkuDescription'
            }
          }
        }
      }
    };
  }
}

module.exports = ResponseMessageEnvelopeApiEntity;
