/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Properties of an artifact source.
 *
 * @extends models['BaseResource']
 */
class ArtifactSource extends models['BaseResource'] {
  /**
   * Create a ArtifactSource.
   * @property {string} [displayName] The display name of the artifact source.
   * @property {string} [uri] The URI of the artifact source.
   * @property {string} [sourceType] The type of the artifact source. Possible
   * values include: 'VsoGit', 'GitHub'
   * @property {string} [folderPath] The folder path of the artifact source.
   * @property {string} [branchRef] The branch reference of the artifact
   * source.
   * @property {string} [securityToken] The security token of the artifact
   * source.
   * @property {string} [status] The status of the artifact source. Possible
   * values include: 'Enabled', 'Disabled'
   * @property {string} [provisioningState] The provisioning status of the
   * resource.
   * @property {string} [id] The identifier of the resource.
   * @property {string} [name] The name of the resource.
   * @property {string} [type] The type of the resource.
   * @property {string} [location] The location of the resource.
   * @property {object} [tags] The tags of the resource.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ArtifactSource
   *
   * @returns {object} metadata of ArtifactSource
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ArtifactSource',
      type: {
        name: 'Composite',
        className: 'ArtifactSource',
        modelProperties: {
          displayName: {
            required: false,
            serializedName: 'properties.displayName',
            type: {
              name: 'String'
            }
          },
          uri: {
            required: false,
            serializedName: 'properties.uri',
            type: {
              name: 'String'
            }
          },
          sourceType: {
            required: false,
            serializedName: 'properties.sourceType',
            type: {
              name: 'String'
            }
          },
          folderPath: {
            required: false,
            serializedName: 'properties.folderPath',
            type: {
              name: 'String'
            }
          },
          branchRef: {
            required: false,
            serializedName: 'properties.branchRef',
            type: {
              name: 'String'
            }
          },
          securityToken: {
            required: false,
            serializedName: 'properties.securityToken',
            type: {
              name: 'String'
            }
          },
          status: {
            required: false,
            serializedName: 'properties.status',
            type: {
              name: 'String'
            }
          },
          provisioningState: {
            required: false,
            serializedName: 'properties.provisioningState',
            type: {
              name: 'String'
            }
          },
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          location: {
            required: false,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = ArtifactSource;
