/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * A virtual machine.
 *
 * @extends models['BaseResource']
 */
class LabVirtualMachine extends models['BaseResource'] {
  /**
   * Create a LabVirtualMachine.
   * @property {string} [notes] The notes of the virtual machine.
   * @property {string} [ownerObjectId] The object identifier of the owner of
   * the virtual machine.
   * @property {string} [createdByUserId] The object identifier of the creator
   * of the virtual machine.
   * @property {string} [createdByUser] The email address of creator of the
   * virtual machine.
   * @property {string} [computeId] The resource identifier (Microsoft.Compute)
   * of the virtual machine.
   * @property {string} [customImageId] The custom image identifier of the
   * virtual machine.
   * @property {string} [osType] The OS type of the virtual machine.
   * @property {string} [size] The size of the virtual machine.
   * @property {string} [userName] The user name of the virtual machine.
   * @property {string} [password] The password of the virtual machine
   * administrator.
   * @property {string} [sshKey] The SSH key of the virtual machine
   * administrator.
   * @property {boolean} [isAuthenticationWithSshKey] A value indicating
   * whether this virtual machine uses an SSH key for authentication.
   * @property {string} [fqdn] The fully-qualified domain name of the virtual
   * machine.
   * @property {string} [labSubnetName] The lab subnet name of the virtual
   * machine.
   * @property {string} [labVirtualNetworkId] The lab virtual network
   * identifier of the virtual machine.
   * @property {boolean} [disallowPublicIpAddress] Indicates whether the
   * virtual machine is to be created without a public IP address.
   * @property {array} [artifacts] The artifacts to be installed on the virtual
   * machine.
   * @property {object} [artifactDeploymentStatus] The artifact deployment
   * status for the virtual machine.
   * @property {string} [artifactDeploymentStatus.deploymentStatus] The
   * deployment status of the artifact.
   * @property {number} [artifactDeploymentStatus.artifactsApplied] The total
   * count of the artifacts that were successfully applied.
   * @property {number} [artifactDeploymentStatus.totalArtifacts] The total
   * count of the artifacts that were tentatively applied.
   * @property {object} [galleryImageReference] The Microsoft Azure Marketplace
   * image reference of the virtual machine.
   * @property {string} [galleryImageReference.offer] The offer of the gallery
   * image.
   * @property {string} [galleryImageReference.publisher] The publisher of the
   * gallery image.
   * @property {string} [galleryImageReference.sku] The SKU of the gallery
   * image.
   * @property {string} [galleryImageReference.osType] The OS type of the
   * gallery image.
   * @property {string} [galleryImageReference.version] The version of the
   * gallery image.
   * @property {string} [provisioningState] The provisioning status of the
   * resource.
   * @property {string} [id] The identifier of the resource.
   * @property {string} [name] The name of the resource.
   * @property {string} [type] The type of the resource.
   * @property {string} [location] The location of the resource.
   * @property {object} [tags] The tags of the resource.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of LabVirtualMachine
   *
   * @returns {object} metadata of LabVirtualMachine
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'LabVirtualMachine',
      type: {
        name: 'Composite',
        className: 'LabVirtualMachine',
        modelProperties: {
          notes: {
            required: false,
            serializedName: 'properties.notes',
            type: {
              name: 'String'
            }
          },
          ownerObjectId: {
            required: false,
            serializedName: 'properties.ownerObjectId',
            type: {
              name: 'String'
            }
          },
          createdByUserId: {
            required: false,
            serializedName: 'properties.createdByUserId',
            type: {
              name: 'String'
            }
          },
          createdByUser: {
            required: false,
            serializedName: 'properties.createdByUser',
            type: {
              name: 'String'
            }
          },
          computeId: {
            required: false,
            serializedName: 'properties.computeId',
            type: {
              name: 'String'
            }
          },
          customImageId: {
            required: false,
            serializedName: 'properties.customImageId',
            type: {
              name: 'String'
            }
          },
          osType: {
            required: false,
            serializedName: 'properties.osType',
            type: {
              name: 'String'
            }
          },
          size: {
            required: false,
            serializedName: 'properties.size',
            type: {
              name: 'String'
            }
          },
          userName: {
            required: false,
            serializedName: 'properties.userName',
            type: {
              name: 'String'
            }
          },
          password: {
            required: false,
            serializedName: 'properties.password',
            type: {
              name: 'String'
            }
          },
          sshKey: {
            required: false,
            serializedName: 'properties.sshKey',
            type: {
              name: 'String'
            }
          },
          isAuthenticationWithSshKey: {
            required: false,
            serializedName: 'properties.isAuthenticationWithSshKey',
            type: {
              name: 'Boolean'
            }
          },
          fqdn: {
            required: false,
            serializedName: 'properties.fqdn',
            type: {
              name: 'String'
            }
          },
          labSubnetName: {
            required: false,
            serializedName: 'properties.labSubnetName',
            type: {
              name: 'String'
            }
          },
          labVirtualNetworkId: {
            required: false,
            serializedName: 'properties.labVirtualNetworkId',
            type: {
              name: 'String'
            }
          },
          disallowPublicIpAddress: {
            required: false,
            serializedName: 'properties.disallowPublicIpAddress',
            type: {
              name: 'Boolean'
            }
          },
          artifacts: {
            required: false,
            serializedName: 'properties.artifacts',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ArtifactInstallPropertiesElementType',
                  type: {
                    name: 'Composite',
                    className: 'ArtifactInstallProperties'
                  }
              }
            }
          },
          artifactDeploymentStatus: {
            required: false,
            serializedName: 'properties.artifactDeploymentStatus',
            type: {
              name: 'Composite',
              className: 'ArtifactDeploymentStatusProperties'
            }
          },
          galleryImageReference: {
            required: false,
            serializedName: 'properties.galleryImageReference',
            type: {
              name: 'Composite',
              className: 'GalleryImageReference'
            }
          },
          provisioningState: {
            required: false,
            serializedName: 'properties.provisioningState',
            type: {
              name: 'String'
            }
          },
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          location: {
            required: false,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = LabVirtualMachine;
