/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Subnet.
 */
class Subnet {
  /**
   * Create a Subnet.
   * @property {string} [resourceId]
   * @property {string} [labSubnetName]
   * @property {string} [allowPublicIp] Possible values include: 'Default',
   * 'Deny', 'Allow'
   */
  constructor() {
  }

  /**
   * Defines the metadata of Subnet
   *
   * @returns {object} metadata of Subnet
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Subnet',
      type: {
        name: 'Composite',
        className: 'Subnet',
        modelProperties: {
          resourceId: {
            required: false,
            serializedName: 'resourceId',
            type: {
              name: 'String'
            }
          },
          labSubnetName: {
            required: false,
            serializedName: 'labSubnetName',
            type: {
              name: 'String'
            }
          },
          allowPublicIp: {
            required: false,
            serializedName: 'allowPublicIp',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Subnet;
